### ISSUE TITLE
Unable to load style.css in Docker environment

### ISSUE THREAD

**Issue by iwbc** [sijad/astro-wordpress#5]
When using wp-env (Docker) to set up a WordPress environment, the contents of the public directory are created as symlinks in the outDir. However, since the original files are not present inside the container, the symlinks are broken.

Is there any recommended solution for this?

**Comment by sijad** [comment]
can you please share your docker command or DockerFile?

**Comment by sijad** [comment]
two new options `publicDirPath` and `devServerTarget` has been added to support Docker:


### `compose.yaml`:
```yaml
services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp:/var/www/html
      - ./public/:/var/www/html/public

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
```

### `astro.config.mjs`:
```javascript
// @ts-check
import { defineConfig, passthroughImageService } from "astro/config";
import wordpress from "astro-wordpress";

// https://astro.build/config
export default defineConfig({
  server: {
    host: "0.0.0.0", // this is required for docket be able send requests
    allowedHosts: ["host.docker.internal"],
  },
  adapter: wordpress({
    devProxyTarget: "http://localhost:8088",
    outDir: "wp/wp-content/themes/astro-wordpress-starter",
    publicDirPath: "/var/www/html/public",
    devServerTarget: "http://host.docker.internal:4321",
  }),
  image: {
    service: passthroughImageService(),
  },
});
```
